/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ForumCellView.java
 *
 * Created on 03/05/2010, 17:02:20
 */
package Forum.Client.ui.TreeView;

import Forum.Client.ui.TreeView.Interfaces.CellViewInterface;
import Forum.PersistentLayer.Interfaces.eMemberType;

/**
 *
 * @author hadur
 */
public class ForumCellView extends javax.swing.JPanel implements CellViewInterface {

    private ForumCell _cell;
    private ForumTree _forumTree;
    private eMemberType _member;
    private String _nick;

    /** Creates new form ForumCellView */
    public ForumCellView(ForumTree forumTree) {
        initComponents();
        _forumTree = forumTree;
    }

    public void updateView(ForumCell cell) {
        _cell = cell;
        lblNick.setText(_cell.getUserName());
        txtSubject.setText(_cell.getSubject());
        txtBody.setText(_cell.getBody());
        setButtons();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNick = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBody = new javax.swing.JTextArea();
        btnModify = new javax.swing.JButton();
        btnReply = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSubject = new javax.swing.JTextField();

        jLabel1.setText("Nick Name:");

        lblNick.setText("********");

        jLabel2.setText("Subject:");

        txtBody.setColumns(20);
        txtBody.setRows(5);
        jScrollPane1.setViewportView(txtBody);

        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        btnReply.setText("Reply");
        btnReply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplyActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNick)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSubject, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReply, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNick, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReply, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        btnModify.setEnabled(false);
        _cell.setBody(txtBody.getText());
        _cell.setSubject(txtSubject.getText());
        _forumTree.modifyMessage(this);
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnReplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplyActionPerformed
        _forumTree.replyToMessage();
    }//GEN-LAST:event_btnReplyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        btnDelete.setEnabled(false);
        _forumTree.deleteMessage();
    }//GEN-LAST:event_btnDeleteActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnReply;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNick;
    private javax.swing.JTextArea txtBody;
    private javax.swing.JTextField txtSubject;
    // End of variables declaration//GEN-END:variables

    public void setViewer(eMemberType member, String nick) {
        _member = member;
        _nick = nick;
        setButtons();
    }

    private void setButtons() {
        btnModify.setEnabled(false);
        btnDelete.setEnabled(false);
        btnReply.setEnabled(false);
        txtBody.setEditable(false);
        txtSubject.setEditable(false);

        switch (_member) {
            case guest:
                break;
            case member:
                btnReply.setEnabled(true);
                if (_cell != null && _nick.equals(_cell.getUserName())) {
                    btnModify.setEnabled(true);
                    txtBody.setEditable(true);
                    txtSubject.setEditable(true);
                }
                break;
            case Moderator:
                btnReply.setEnabled(true);
                btnModify.setEnabled(true);
                txtBody.setEditable(true);
                btnDelete.setEnabled(true);
                txtSubject.setEditable(true);
                break;
            case Admin:
                btnReply.setEnabled(true);
                btnModify.setEnabled(true);
                btnDelete.setEnabled(true);
                txtBody.setEditable(true);
                txtSubject.setEditable(true);
                break;
        }
    }

    public void Modified() {
        setButtons();
    }
}
