package Forum.PersistentLayer;
// Generated 02:47:58 02/05/2010 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer number;
     private String title;
     private String body;
     private String author;
     private Date dataOfAdd;
     private Date dateOfEdit;
     private Integer idFather;

    public Message() {
    }

	
    public Message(String author, Date dataOfAdd, Date dateOfEdit) {
        this.author = author;
        this.dataOfAdd = dataOfAdd;
        this.dateOfEdit = dateOfEdit;
    }
    public Message(String title, String body, String author, Date dataOfAdd, Date dateOfEdit, Integer idFather) {
       this.title = title;
       this.body = body;
       this.author = author;
       this.dataOfAdd = dataOfAdd;
       this.dateOfEdit = dateOfEdit;
       this.idFather = idFather;
    }
   
    public Integer getNumber() {
        return this.number;
    }
    
    public void setNumber(Integer number) {
        this.number = number;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Date getDataOfAdd() {
        return this.dataOfAdd;
    }
    
    public void setDataOfAdd(Date dataOfAdd) {
        this.dataOfAdd = dataOfAdd;
    }
    public Date getDateOfEdit() {
        return this.dateOfEdit;
    }
    
    public void setDateOfEdit(Date dateOfEdit) {
        this.dateOfEdit = dateOfEdit;
    }
    public Integer getIdFather() {
        return this.idFather;
    }
    
    public void setIdFather(Integer idFather) {
        this.idFather = idFather;
    }




}


