/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 24/04/2010, 12:05:15
 */

package Forum.Client.ui;

import Forum.Client.ControllerLayer.ControllerHandler;
import Forum.Client.ui.TreeView.ForumTree;
import java.awt.Dimension;

import javax.swing.DefaultListModel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Eden
 */
public class MainFrame extends javax.swing.JFrame  {
public ControllerHandler m_pipe;

    /** Creates new form MainFrame */
    public MainFrame(String title) {
        super(title);
        initComponents();
        ForumTree tree = new ForumTree(this);
        this.loginLabel.setVisible(false);
        this.LogoutB.setVisible(false);
        this.AdminPanel.setVisible(false);
        TreePane.setViewportView(tree.getForumTreeUI());      
        this.RegPanel.setVisible(false);
        this.m_pipe = tree.getPipe();
         this.m_pipe.getOnlineMembers(this);

       int delay = 10000; //milliseconds
       ActionListener taskPerformer = new ActionListener() {
       public void actionPerformed(ActionEvent evt) {
          m_pipe.getOnlineMembers(null);
      }
  };
  new Timer(delay, taskPerformer).start();
    }




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        bRegister = new javax.swing.JButton();
        bLogin = new javax.swing.JButton();
        tUsername = new javax.swing.JTextField();
        tPassword = new javax.swing.JPasswordField();
        tPassL = new javax.swing.JLabel();
        lUsername = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        LogoutB = new javax.swing.JButton();
        BottomPanel = new javax.swing.JPanel();
        SearchPanel = new javax.swing.JPanel();
        pSearchByAuthor = new javax.swing.JPanel();
        tSearchAuther = new javax.swing.JTextField();
        bSearchAuthor = new javax.swing.JButton();
        lAuther = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        pSearchByPharse = new javax.swing.JPanel();
        tSearchPharse = new javax.swing.JTextField();
        bSearchPharse = new javax.swing.JButton();
        lPharse = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        StatusPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jOnlineUsersTextArea = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        TreePane = new javax.swing.JScrollPane();
        RegPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Fname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Lname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Nick = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Uname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Pass = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        rePass = new javax.swing.JPasswordField();
        RegButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        AdminPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ulist = new javax.swing.JList();
        Jupgrade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36));
        jLabel1.setText("Tapuach Forum");

        bRegister.setText("Register");
        bRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegisterActionPerformed(evt);
            }
        });

        bLogin.setText("Log in");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        tPassword.setColumns(8);

        tPassL.setText("Password:");

        lUsername.setText("Username:");

        LogoutB.setText("Logout");
        LogoutB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tPassL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bRegister))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LogoutB)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPassL)
                    .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLogin)
                    .addComponent(bRegister)
                    .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lUsername))
                .addGap(18, 18, 18)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutB))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pSearchByAuthor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Search by Author"));

        tSearchAuther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSearchAutherActionPerformed(evt);
            }
        });

        bSearchAuthor.setText("Search");
        bSearchAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearchAuthorActionPerformed(evt);
            }
        });

        lAuther.setText("Author:");

        jLabel5.setText("From:");

        jLabel6.setText("To:");

        javax.swing.GroupLayout pSearchByAuthorLayout = new javax.swing.GroupLayout(pSearchByAuthor);
        pSearchByAuthor.setLayout(pSearchByAuthorLayout);
        pSearchByAuthorLayout.setHorizontalGroup(
            pSearchByAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchByAuthorLayout.createSequentialGroup()
                .addComponent(lAuther)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tSearchAuther, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bSearchAuthor)
                .addContainerGap())
        );
        pSearchByAuthorLayout.setVerticalGroup(
            pSearchByAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchByAuthorLayout.createSequentialGroup()
                .addGroup(pSearchByAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lAuther)
                    .addComponent(tSearchAuther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSearchAuthor))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pSearchByPharse.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Search by Pharse"));

        bSearchPharse.setText("Search");
        bSearchPharse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearchPharseActionPerformed(evt);
            }
        });

        lPharse.setText("Pharse:");

        jLabel3.setText("From:");

        jLabel4.setText("To:");

        javax.swing.GroupLayout pSearchByPharseLayout = new javax.swing.GroupLayout(pSearchByPharse);
        pSearchByPharse.setLayout(pSearchByPharseLayout);
        pSearchByPharseLayout.setHorizontalGroup(
            pSearchByPharseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSearchByPharseLayout.createSequentialGroup()
                .addComponent(lPharse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tSearchPharse, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(bSearchPharse)
                .addContainerGap())
        );
        pSearchByPharseLayout.setVerticalGroup(
            pSearchByPharseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchByPharseLayout.createSequentialGroup()
                .addGroup(pSearchByPharseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSearchPharse)
                    .addComponent(tSearchPharse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPharse))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPanelLayout.createSequentialGroup()
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pSearchByPharse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pSearchByAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addComponent(pSearchByAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pSearchByPharse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jOnlineUsersTextArea.setColumns(20);
        jOnlineUsersTextArea.setEditable(false);
        jOnlineUsersTextArea.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jOnlineUsersTextArea.setRows(5);
        jScrollPane1.setViewportView(jOnlineUsersTextArea);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Online users:");

        javax.swing.GroupLayout StatusPanelLayout = new javax.swing.GroupLayout(StatusPanel);
        StatusPanel.setLayout(StatusPanelLayout);
        StatusPanelLayout.setHorizontalGroup(
            StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        StatusPanelLayout.setVerticalGroup(
            StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout BottomPanelLayout = new javax.swing.GroupLayout(BottomPanel);
        BottomPanel.setLayout(BottomPanelLayout);
        BottomPanelLayout.setHorizontalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(StatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        BottomPanelLayout.setVerticalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StatusPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel2.setText("First Name:");

        Fname.setColumns(10);
        Fname.setToolTipText("your first name");

        jLabel7.setText("Last Name:");

        Lname.setColumns(10);
        Lname.setToolTipText("your family name");

        jLabel8.setText("Email:");

        email.setColumns(15);
        email.setToolTipText("email");

        jLabel9.setText("Nickname:");

        Nick.setToolTipText("your nickname in the forum");

        jLabel10.setText("Username:");

        Uname.setToolTipText("username for login purposes");

        jLabel11.setText("Password:");

        Pass.setColumns(8);
        Pass.setToolTipText("the password must be 8 characters");

        jLabel12.setText("Re-enter Password:");

        rePass.setToolTipText("retype password");

        RegButton.setText("Register");
        RegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegPanelLayout = new javax.swing.GroupLayout(RegPanel);
        RegPanel.setLayout(RegPanelLayout);
        RegPanelLayout.setHorizontalGroup(
            RegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(RegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RegPanelLayout.createSequentialGroup()
                        .addComponent(RegButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelButton))
                    .addGroup(RegPanelLayout.createSequentialGroup()
                        .addGroup(RegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(RegPanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel8))
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addGroup(RegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addGroup(RegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nick, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addGroup(RegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Fname)
                                .addComponent(email)
                                .addComponent(Lname, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                .addComponent(Uname)
                                .addComponent(rePass, 0, 0, Short.MAX_VALUE)
                                .addComponent(Pass, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        RegPanelLayout.setVerticalGroup(
            RegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(RegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(RegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(RegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(RegButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(Ulist);

        Jupgrade.setText("Upgrade");
        Jupgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JupgradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jupgrade)
                .addGap(20, 20, 20))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jupgrade))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TreePane, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TreePane, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RegPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegisterActionPerformed
        // TODO add your handling code here:
        this.RegPanel.setVisible(true);
        this.SearchPanel.setVisible(false);
        this.TreePane.setVisible(false);
        this.StatusPanel.setVisible(false);
        this.LoginPanel.setVisible(false);
    }//GEN-LAST:event_bRegisterActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        String userNameText = tUsername.getText();
        tUsername.selectAll();
        String passwordText = new String(tPassword.getPassword());
        tPassword.selectAll();
        this.m_pipe.login(userNameText, passwordText, this);
        
    }//GEN-LAST:event_bLoginActionPerformed

    public void loginSuccess(String user)
    {
        this.lUsername.setVisible(false);
        this.tUsername.setVisible(false);
        this.tUsername.setText("");
        this.tPassL.setVisible(false);
        this.tPassword.setVisible(false);
        this.tPassword.setText("");
        this.bLogin.setVisible(false);
        this.bRegister.setVisible(false);
        this.loginLabel.setText("welcome "+user);
        this.loginLabel.setVisible(true);
        this.LogoutB.setVisible(true);

        if(user.compareTo("admin") ==0){
               this.AdminPanel.setVisible(true);
               this.m_pipe.getMembers(this);
        }

    }

    public void setOnlineUsers(String onlineUsers)
    {
       this.jOnlineUsersTextArea.setText(onlineUsers);

    }


    public void RefreshUMembers( String lm)
    {
         DefaultListModel dm = new DefaultListModel();
        String[] st = lm.split(";");

        for(int i=0;i<st.length;i++){
            dm.addElement(st[i]);
        }
        Ulist.setModel(dm);
        

    }
    




    private void tSearchAutherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSearchAutherActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tSearchAutherActionPerformed

    private void bSearchAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchAuthorActionPerformed
        String autherText = tSearchAuther.getText();
        tSearchAuther.selectAll();
    }//GEN-LAST:event_bSearchAuthorActionPerformed

    private void bSearchPharseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchPharseActionPerformed
        String pharseText = tSearchPharse.getText();
        tSearchPharse.selectAll();
}//GEN-LAST:event_bSearchPharseActionPerformed

    private void RegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegButtonActionPerformed
          if(correctInput()){
              String tFname = Fname.getText();
              String tLname = Lname.getText();
              String tEmail = email.getText();
              String tUname = Uname.getText();
              String tNick = Nick.getText();
              String tPass = new String(Pass.getPassword());

             m_pipe.register(tFname, tLname, tNick, tEmail, tUname, tPass, null);
             
         
     


          }


}//GEN-LAST:event_RegButtonActionPerformed

    private boolean correctInput(){

            if(this.Fname.getText().compareTo("") ==0) {
                  JOptionPane.showMessageDialog(this,   "please enter a first name",    "Error",    JOptionPane.WARNING_MESSAGE);
                  return false;
            }
               if(this.Lname.getText().compareTo("") ==0) {
                  JOptionPane.showMessageDialog(this,   "please enter a last name",    "Error",    JOptionPane.WARNING_MESSAGE);
                  return false;
            }
            
               if(this.email.getText().compareTo("") ==0) {                 //.matches("[a-zA-Z0-9]+@([a-zA-Z0-9]+)[.]{1}([a-zA-Z.]+)")) {
                  JOptionPane.showMessageDialog(this,   "wrong email adress",    "Error",    JOptionPane.WARNING_MESSAGE);
                  return false;
            }

             if(this.Uname.getText().compareTo("") ==0) {
                  JOptionPane.showMessageDialog(this,   "please enter a username",    "Error",    JOptionPane.WARNING_MESSAGE);
                  return false;
            }

             if(this.Nick.getText().compareTo("") ==0) {
                  JOptionPane.showMessageDialog(this,   "please enter a nickname",    "Error",    JOptionPane.WARNING_MESSAGE);
                  return false;
            }

            String p1 = new String(this.Pass.getPassword()); String p2 = new String(this.rePass.getPassword());
             if(p1.compareTo(p2)!=0){
                  JOptionPane.showMessageDialog(this,   "passwords don't match",    "Error",    JOptionPane.WARNING_MESSAGE);
                  return false;
             }
            return true;
            }


public void RegSuccess()
{
    JOptionPane.showMessageDialog(this,   "Registration Successful",    "Success",    JOptionPane.INFORMATION_MESSAGE);
        this.Fname.setText("");
         this.Lname.setText("");
        this.email.setText("");
        this.Nick.setText("");
        this.Uname.setText("");
        this.Pass.setText("");
        this.rePass.setText("");
        this.RegPanel.setVisible(false);
        this.SearchPanel.setVisible(true);
        this.TreePane.setVisible(true);
        this.StatusPanel.setVisible(true);
        this.LoginPanel.setVisible(true);
}




    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.Fname.setText("");
        this.Lname.setText(""); 
        this.email.setText(""); 
        this.Nick.setText(""); 
        this.Uname.setText(""); 
        this.Pass.setText(""); 
        this.rePass.setText("");
        this.RegPanel.setVisible(false);
        this.SearchPanel.setVisible(true);
        this.TreePane.setVisible(true);
        this.StatusPanel.setVisible(true);
        this.LoginPanel.setVisible(true);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void LogoutBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBActionPerformed
    m_pipe.logoff(this);
    }//GEN-LAST:event_LogoutBActionPerformed

 

    private void JupgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JupgradeActionPerformed
        m_pipe.UpgradeUser(((String)(Ulist.getSelectedValue())), null);

    }//GEN-LAST:event_JupgradeActionPerformed

    public void upgradeSuccess()
    {
         JOptionPane.showMessageDialog(this,   "Upgrade Successful",    "Success",    JOptionPane.INFORMATION_MESSAGE);
         m_pipe.getMembers(this);
    }
    
    public void LogoutSuccess(){
         this.lUsername.setVisible(true);
        this.tUsername.setVisible(true);
        this.tPassL.setVisible(true);
        this.tPassword.setVisible(true);
        this.bLogin.setVisible(true);
        this.bRegister.setVisible(true);
        this.loginLabel.setText("");
        this.loginLabel.setVisible(false);
        this.LogoutB.setVisible(false);
        this.Ulist.setModel(new DefaultListModel());
        this.AdminPanel.setVisible(false);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
         //ForumTree tree = new ForumTree();
         MainFrame mainFrame = new MainFrame("Tapuach Forum");
      //   mainFrame.RegisterPanel.setVisible(false);
         //mainFrame.TreePane.setViewportView(tree.getForumTreeUI());
         mainFrame.setSize(new Dimension(1200,800));
         mainFrame.setResizable(false);
         mainFrame.setVisible(true);
         mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField Fname;
    private javax.swing.JButton Jupgrade;
    private javax.swing.JTextField Lname;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JButton LogoutB;
    private javax.swing.JTextField Nick;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JButton RegButton;
    private javax.swing.JPanel RegPanel;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JPanel StatusPanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JScrollPane TreePane;
    private javax.swing.JList Ulist;
    private javax.swing.JTextField Uname;
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bRegister;
    private javax.swing.JButton bSearchAuthor;
    private javax.swing.JButton bSearchPharse;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jOnlineUsersTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lAuther;
    private javax.swing.JLabel lPharse;
    private javax.swing.JLabel lUsername;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel pSearchByAuthor;
    private javax.swing.JPanel pSearchByPharse;
    private javax.swing.JPasswordField rePass;
    private javax.swing.JLabel tPassL;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tSearchAuther;
    private javax.swing.JTextField tSearchPharse;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables


}
