/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on 03/05/2010, 17:47:18
 */
package Forum.Client.ui;

import Forum.Client.ControllerLayer.ControllerHandler;
import Forum.Client.ui.TreeView.ForumTree;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author lironkat
 */
public class Main extends javax.swing.JFrame {

    private ControllerHandler m_pipe;

    /** Creates new form Main */
    public Main(String title) {
           super(title);
        initComponents();
        ForumTree tree = new ForumTree(this);
        this.TreePanel.setViewportView(tree.getForumTreeUI());
        this.m_pipe = tree.getPipe();
        this.loginPanel.addParent(this);
        this.statusPanel.addParent(this);
        this.searchPanel.addParent(this);
        this.logoutPanel.addParent(this);
        this.logoutPanel.setVisible(false);
        this.m_pipe.getOnlineMembers(this);
        int delay = 10000; //milliseconds
        ActionListener taskPerformer = new ActionListener() {

            public void actionPerformed(ActionEvent evt) {
                m_pipe.getOnlineMembers(null);
            }
        };
        new Timer(delay, taskPerformer).start();

    }

    public void LogoutSuccess() {
        this.logoutPanel.setVisible(false);
        this.loginPanel.getTUsername().setText("");
        this.loginPanel.getTPassword().setText("");
        this.loginPanel.setVisible(true);
    }

    public void RefreshUMembers(String _lm) {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    public void RegSuccess() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    public void loginSuccess(String user) {
        this.loginPanel.setVisible(false);
        this.logoutPanel.setuser(user);
        logoutPanel.setVisible(true);
    }

    public void setOnlineUsers(String onlineUsers) {
        this.getStatusPanel1().getJTextArea1().setText(onlineUsers);
    }

    public void upgradeSuccess() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forumLabel = new javax.swing.JLabel();
        loginPanel = new Forum.Client.ui.LoginPanel();
        searchPanel = new Forum.Client.ui.SearchPanel();
        TreePanel = new javax.swing.JScrollPane();
        statusPanel = new Forum.Client.ui.StatusPanel();
        logoutPanel = new Forum.Client.ui.LogoutPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        forumLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        forumLabel.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\windows\\My Documents\\NetBeansProjects\\test\\test\\images\\tapuachLogo2.gif")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(forumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(TreePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TreePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(forumLabel)
                .addGap(703, 703, 703))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         Main main = new Main("Tapuach Forum");
      //   mainFrame.RegisterPanel.setVisible(false);
         //mainFrame.TreePane.setViewportView(tree.getForumTreeUI());
         main.setSize(new Dimension(1200,800));
         main.setResizable(false);
         main.setVisible(true);
         main.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TreePanel;
    private javax.swing.JLabel forumLabel;
    private Forum.Client.ui.LoginPanel loginPanel;
    private Forum.Client.ui.LogoutPanel logoutPanel;
    private Forum.Client.ui.SearchPanel searchPanel;
    private Forum.Client.ui.StatusPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the m_pipe
     */
    public ControllerHandler getM_pipe() {
        return m_pipe;
    }

    /**
     * @return the loginPanel1
     */
    public Forum.Client.ui.LoginPanel getLoginPanel1() {
        return loginPanel;
    }

    /**
     * @return the searchPanel1
     */
    public Forum.Client.ui.SearchPanel getSearchPanel1() {
        return searchPanel;
    }

    /**
     * @return the statusPanel1
     */
    public Forum.Client.ui.StatusPanel getStatusPanel1() {
        return statusPanel;
    }
}
