/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on 03/05/2010, 17:47:18
 */
package Forum.Client.ui;

import Forum.Client.ControllerLayer.ControllerHandler;
import Forum.Client.ui.TreeView.ForumTree;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author lironkat
 */
public class Main extends javax.swing.JFrame {

    private ControllerHandler m_pipe;

    /** Creates new form Main */
    public Main(String title) {
           super(title);
        initComponents();
        ForumTree tree = new ForumTree(this);
        this.TreePanel.setViewportView(tree.getForumTreeUI());
        this.m_pipe = tree.getPipe();
        this.addMainToPanels();
        this.upgradeUsersPanel.setVisible(false);
        this.logoutPanel.setVisible(false);
        this.registrationPanel.setVisible(false);
        this.m_pipe.getOnlineMembers(this);
        int delay = 10000; //milliseconds
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                m_pipe.getOnlineMembers(null);
            }
        };
        new Timer(delay, taskPerformer).start();

    }

    private void addMainToPanels(){
        this.loginPanel.addParent(this);
        this.statusPanel.addParent(this);
        this.searchPanel.addParent(this);
        this.logoutPanel.addParent(this);
        this.registrationPanel.addParent(this);
        this.upgradeUsersPanel.addParent(this);
    }

    public void LogoutSuccess() {
        this.logoutPanel.setVisible(false);
        this.loginPanel.getTUsername().setText("");
        this.loginPanel.getTPassword().setText("");
        this.loginPanel.setVisible(true);
    }

    public void RefreshUMembers(String _lm) {
        DefaultListModel dm = new DefaultListModel();
        String[] st = _lm.split(";");

        for(int i=0;i<st.length;i++){
            dm.addElement(st[i]);
        }
        this.upgradeUsersPanel.getMemberList().setModel(dm);
    }

    public void RegSuccess() {
        JOptionPane.showMessageDialog(this,   "Registration Successful",    "Success",    JOptionPane.INFORMATION_MESSAGE);
        this.getRegistrationPanel().clearFields();
        this.getRegistrationPanel().setVisible(false);
        this.TreePanel.setVisible(true);
        this.searchPanel.setVisible(true);
        this.statusPanel.setVisible(true);
    }

    public void loginSuccess(String user) {
        this.loginPanel.setVisible(false);
        this.logoutPanel.setuser(user);
        logoutPanel.setVisible(true);
    }

    public void setOnlineUsers(String onlineUsers) {
        this.getStatusPanel1().getJTextArea1().setText(onlineUsers);
    }

    public void upgradeSuccess() {
        JOptionPane.showMessageDialog(this,   "Upgrade Successful",    "Success",    JOptionPane.INFORMATION_MESSAGE);
        this. m_pipe.getMembers(this);
    }


    public void showResults(String results){
       //TO-DO
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forumLabel = new javax.swing.JLabel();
        loginPanel = new Forum.Client.ui.LoginPanel();
        registrationPanel = new Forum.Client.ui.RegistrationPanel();
        TreePanel = new javax.swing.JScrollPane();
        logoutPanel = new Forum.Client.ui.LogoutPanel();
        searchPanel = new Forum.Client.ui.SearchPanel();
        statusPanel = new Forum.Client.ui.StatusPanel();
        upgradeUsersPanel = new Forum.Client.ui.upgradeUsersPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        forumLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        forumLabel.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\windows\\My Documents\\NetBeansProjects\\tapuachforum\\images\\tapuachLogo4.gif")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TreePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upgradeUsersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(forumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(491, 491, 491))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(registrationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1233, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(forumLabel)
                    .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upgradeUsersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TreePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(134, 134, 134)
                    .addComponent(registrationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(270, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         Main main = new Main("Tapuach Forum v1.0");
         main.setSize(new Dimension(1200,800));
         main.setResizable(false);
         main.setVisible(true);
         main.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TreePanel;
    private javax.swing.JLabel forumLabel;
    private Forum.Client.ui.LoginPanel loginPanel;
    private Forum.Client.ui.LogoutPanel logoutPanel;
    private Forum.Client.ui.RegistrationPanel registrationPanel;
    private Forum.Client.ui.SearchPanel searchPanel;
    private Forum.Client.ui.StatusPanel statusPanel;
    private Forum.Client.ui.upgradeUsersPanel upgradeUsersPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the m_pipe
     */
    public ControllerHandler getM_pipe() {
        return m_pipe;
    }

    /**
     * @return the loginPanel1
     */
    public Forum.Client.ui.LoginPanel getLoginPanel1() {
        return loginPanel;
    }

    /**
     * @return the searchPanel1
     */
    public Forum.Client.ui.SearchPanel getSearchPanel1() {
        return searchPanel;
    }

    /**
     * @return the statusPanel1
     */
    public Forum.Client.ui.StatusPanel getStatusPanel1() {
        return statusPanel;
    }

    /**
     * @return the registrationPanel
     */
    public Forum.Client.ui.RegistrationPanel getRegistrationPanel() {
        return registrationPanel;
    }

    /**
     * @return the TreePanel
     */
    public javax.swing.JScrollPane getTreePanel() {
        return TreePanel;
    }

    /**
     * @return the upgradeUsersPanel
     */
    public Forum.Client.ui.upgradeUsersPanel getUpgradeUsersPanel() {
        return upgradeUsersPanel;
    }
}
