/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PagingPanel.java
 *
 * Created on 21-Jul-2010, 23:02:33
 */
package Forum.Client.ui;

/**
 *
 * @author kipi
 */
public class PagingPanel extends javax.swing.JPanel {

    private Main m_main = null;
    private int m_curPage = 1;
    private int m_PageCount = 1;
    private boolean m_isPassMax = false;

    /** Creates new form PagingPanel */
    public PagingPanel() {
        initComponents();
    }

    public void setMain(Main main) {
        m_main = main;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblPage = new javax.swing.JLabel();
        btnForward = new javax.swing.JButton();

        btnBack.setText("<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblPage.setText("00 / 00");

        btnForward.setText(">");
        btnForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForwardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPage)
                .addGap(18, 18, 18)
                .addComponent(btnForward)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnBack)
                .addComponent(lblPage)
                .addComponent(btnForward))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MovePage(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForwardActionPerformed

        MovePage(true);
    }//GEN-LAST:event_btnForwardActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnForward;
    private javax.swing.JLabel lblPage;
    // End of variables declaration//GEN-END:variables

    public void UpdateView() {
        if (m_main != null) {
            m_PageCount = m_main.getForumTree().getNumbmerOfPages();
            lblPage.setText(m_curPage + " / " + m_PageCount);
            btnBack.setEnabled(m_curPage != 1);
            btnForward.setEnabled(m_curPage != m_PageCount);
            if (m_curPage > m_PageCount) {
                m_curPage--;
                m_main.getForumTree().MoveDisplayFrom(false);
                m_isPassMax = true;
            }else
                m_isPassMax=false;
        }
    }

    public boolean isPassMax() {
        return m_isPassMax;
    }

    private void MovePage(boolean forword) {
        if (forword) {
            m_curPage++;
        } else {
            m_curPage--;
        }
        UpdateView();
        m_main.getForumTree().MoveDisplayFrom(forword);
        m_main.getM_pipe().refreshForum(m_main);
    }
}
