/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchResultPanel.java
 *
 * Created on 05/05/2010, 20:05:10
 */
package Forum.Client.ui;

import Forum.DomainLayer.Interfaces.MessageInterface;
import Forum.DomainLayer.Message;
import Forum.DomainLayer.SearchEngine.SearchHit;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author lironkat
 */
public class SearchResultPanel extends javax.swing.JPanel {

    private Main _parent;
    private JTable _resultTable;
    private DefaultTableModel _tableModel;

    /** Creates new form SearchResultPanel */
    public SearchResultPanel() {
        initComponents();
        CreateTable();
    }

    public void addMessageToTable(SearchHit hit) {
        MessageInterface m = hit.getMessage();
        int id = m.getIndex();
        String auther = m.getNickname();
        String subject = m.getSubject();
        String context = m.getBody();
        Date dateAdded = m.getWriteDate();
        TableModel model = this.resultTable.getModel();
        ((DefaultTableModel) model).addRow(new Object[]{id, auther, subject, context, dateAdded,hit.getScore()});
    }

    void addParent(Main main) {
        this._parent = main;
    }

    private void CreateTable() {
        String col[] = {"Auther", "Subject", "Context", "Date added","score"};
        this._tableModel = new DefaultTableModel(null, col);
        this._resultTable = new JTable(this._tableModel);
        this.tablePanel.add(this._resultTable);
        resultTable.removeColumn(resultTable.getColumnModel().getColumn(0));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bClose = new javax.swing.JButton();
        tablePanel = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        btnGo = new javax.swing.JButton();

        bClose.setText("Close");
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Auther", "Subject", "Context", "Date Added", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePanel.setViewportView(resultTable);

        btnGo.setText("Go to message");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGo)
                        .addGap(18, 18, 18)
                        .addComponent(bClose))
                    .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bClose)
                    .addComponent(btnGo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        back();
}//GEN-LAST:event_bCloseActionPerformed
    private void back() {
        Main main = this.getMain();
        main.getTreePanel().setVisible(true);
        main.getSearchPanel1().setVisible(true);
        main.getStatusPanel1().setVisible(true);
        main.getPagingPanel().setVisible(true);
        if (main.isAdminLogged())
            main.getUpgradeUsersPanel().setVisible(true);
        main.getSearchResultPanel1().setVisible(false);
    }
    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        int row = resultTable.getSelectedRow();
        if (row != -1) {
            Integer id = (Integer) ((DefaultTableModel) resultTable.getModel()).getValueAt(row, 0);
            this.getMain().getForumTree().setPath(id);
        }
        back();
}//GEN-LAST:event_btnGoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JButton btnGo;
    private javax.swing.JTable resultTable;
    private javax.swing.JScrollPane tablePanel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the _parent
     */
    public Main getMain() {
        return _parent;
    }

    public void resetResults() {
        int rowCount = ((DefaultTableModel) resultTable.getModel()).getRowCount();
        for (int i = 0; i < rowCount; i++) {
            ((DefaultTableModel) resultTable.getModel()).removeRow(0);
        }
    }

    /**
     *
     * @return the resultTable
     */
    public javax.swing.JTable getResultTable() {
        return this._resultTable;
    }
}
