/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * upgradeUsersPanel.java
 *
 * Created on 05/05/2010, 15:42:02
 */

package Forum.Client.ui;


/**
 *
 * @author windows
 */
public class upgradeUsersPanel extends javax.swing.JPanel {

     private Main _parent ;

    /** Creates new form upgradeUsersPanel */
    public upgradeUsersPanel() {
        initComponents();
    }

        void addParent(Main main) {
          this._parent = main;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JScrollPane1 = new javax.swing.JScrollPane();
        memberList = new javax.swing.JList();
        bUpgrade = new javax.swing.JButton();
        lMember = new javax.swing.JLabel();

        memberList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        JScrollPane1.setViewportView(memberList);

        bUpgrade.setText("Upgrade");
        bUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpgradeActionPerformed(evt);
            }
        });

        lMember.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        lMember.setText("Members' List");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lMember))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(JScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(bUpgrade)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lMember)
                .addGap(18, 18, 18)
                .addComponent(JScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bUpgrade)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpgradeActionPerformed
        this.getMain().getM_pipe().UpgradeUser(((String)(this.getMemberList().getSelectedValue())), null);        // TODO add your handling code here:
    }//GEN-LAST:event_bUpgradeActionPerformed

    public Main getMain() {
        return _parent;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane1;
    private javax.swing.JButton bUpgrade;
    private javax.swing.JLabel lMember;
    private javax.swing.JList memberList;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the memberList
     */
    public javax.swing.JList getMemberList() {
        return memberList;
    }

}
